# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-13 17:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20160713_1626'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='products',
            table='Products',
        ),
    ]
